""" A set of known words and end-of-word patterns for the spellchecker. """

words = {
    "automata",
    "calc",
    "CDF",
    "CDFs",
    "Ciw",
    "DES",
    "dt",
    "erlang",
    "HB",
    "hypoexponential",
    "ieeetr",
    "ij",
    "LHS",
    "Markovian",
    "math",
    "memoryless",
    "Michalis",
    "Panayides",
    "pre",
    "queueing",
    "RHS",
    "stochasticity",
    "th",
    "Zx",
}
